default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram_clone02_development

test:
  <<: *default
  database: instagram_clone02_test

production:
  <<: *default
  database: instagram_clone02_production
  username: instagram_clone02
  password: <%= ENV['INSTAGRAM_CLONE02_DATABASE_PASSWORD'] %>
